### ISSUE TITLE
Save file and standalone app running

### ISSUE THREAD

**Issue by danieltang3434** [HeliosInteractive/OpenRoC#4]
I have 2 questions here:
1. Is it possible to build the app that runs as standalone without installation like Restart On Crash?
2. Is there a way to export the all the app saved setting and the monitor list like Restart On Crash?

BTW, many thanks to the author for building such fantastic app, I appreciate the work done.

**Comment by 3p3r** [comment]
Hey @danieltang3434 thanks for your interest in this project. This is a very old piece of code. So I try my best to answer your questions to the best of my knowledge:

1. Is it possible to build the app that runs as standalone without installation like Restart On Crash? **that was the idea. yes. AFAIK you can compile this in Visual Studio as an standalone app by default.**

2. Is there a way to export the all the app saved setting and the monitor list like Restart On Crash? **the main configuration file is saved as an XML AFAIK. take a look at here**: https://github.com/HeliosInteractive/OpenRoC/blob/eeebdab250a140e3b7eb40c6d2324d350c14eb06/OpenRoC/Settings.cs#L190

**Comment by danieltang3434** [comment]
Thank you for the answer! I will look into it.
